spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        open-in-view: true
    datasource:
        # 使用的数据库是啥 主要用来判断使用哪个schema-{platform}.sql
        platform: h2
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.h2.Driver
        druid:
            url: jdbc:h2:mem:template1;USER=sa;PASSWORD=123
            username: sa
            password: 123
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    #merge-sql: true
                wall:
                    config:
                      multi-statement-allow: true
    h2:
        console:
            enabled: true

management:
    security:
      enabled: false